# Two sigma financial news 

https://www.kaggle.com/c/two-sigma-financial-news/data

In [2]:
import pandas as pd
mktdata_df = pd.read_csv('/Users/hao.yan/data/two-sigma-financial-news/marketdata_sample.csv')
mktdata_df.head()

,time,assetCode,assetName,universe,volume,close,open,returnsClosePrevRaw1,returnsOpenPrevRaw1,returnsClosePrevMktres1,returnsOpenPrevMktres1,returnsClosePrevRaw10,returnsOpenPrevRaw10,returnsClosePrevMktres10,returnsOpenPrevMktres10,returnsOpenNextMktres10
0,2007-02-01 22:00:00+00:00,A.N,Agilent Technologies Inc,1.0,2606900.0,32.19,32.17,0.005938,0.005312,NaN,NaN,-0.001860,0.000622,NaN,NaN,0.034672
1,2007-02-01 22:00:00+00:00,AAI.N,AirTran Holdings Inc,0.0,2051600.0,11.12,11.08,0.004517,-0.007168,NaN,NaN,-0.078708,-0.088066,NaN,NaN,0.027803
2,2007-02-01 22:00:00+00:00,AAP.N,Advance Auto Parts Inc,1.0,1164800.0,37.51,37.99,-0.011594,0.025648,NaN,NaN,0.014332,0.045405,NaN,NaN,0.024433
3,2007-02-01 22:00:00+00:00,AAPL.O,Apple Inc,1.0,23747329.0,84.74,86.23,-0.011548,0.016324,NaN,NaN,-0.048613,-0.037182,NaN,NaN,-0.007425
4,2007-02-01 22:00:00+00:00,ABB.N,ABB Ltd,1.0,1208600.0,18.02,18.01,0.011791,0.025043,NaN,NaN,0.012929,0.020397,NaN,NaN,-0.017994

In [4]:
news_df  = pd.read_csv('/Users/hao.yan/data/two-sigma-financial-news/news_sample.csv')
news_df.head()

,time,sourceTimestamp,firstCreated,sourceId,headline,urgency,takeSequence,provider,subjects,audiences,...,noveltyCount12H,noveltyCount24H,noveltyCount3D,noveltyCount5D,noveltyCount7D,volumeCounts12H,volumeCounts24H,volumeCounts3D,volumeCounts5D,volumeCounts7D
0,2007-01-01 04:29:32+00:00,2007-01-01 04:29:32+00:00,2007-01-01 04:29:32+00:00,e58c6279551b85cf,China's Daqing pumps 43.41 mln tonnes of oil i...,3,1,RTRS,"{'CRU', 'CN', 'RTRS', 'ENR', 'LEN', 'EMRG', 'N...","{'O', 'Z', 'OIL'}",...,0,0,0,0,0,0,0,3,6,7
1,2007-01-01 07:03:35+00:00,2007-01-01 07:03:34+00:00,2007-01-01 07:03:34+00:00,5a31c4327427f63f,"FEATURE-In kidnapping, finesse works best",3,1,RTRS,"{'BD', 'INS', 'LATAM', 'CA', 'US', 'MX', 'IL',...","{'PGE', 'PCU', 'PCO', 'DNP', 'MD', 'E', 'G', '...",...,1,1,1,1,1,1,1,3,3,3
2,2007-01-01 11:29:56+00:00,2007-01-01 11:29:56+00:00,2007-01-01 11:29:56+00:00,1cefd27a40fabdfe,PRESS DIGEST - Wall Street Journal - Jan 1,3,1,RTRS,"{'IQ', 'RO', 'US', 'ID', 'RET', 'RTRS', 'ENR',...","{'M', 'PMF', 'DNP', 'PTD', 'T', 'E', 'D', 'PSC...",...,0,0,0,0,0,0,0,5,11,17
3,2007-01-01 12:08:37+00:00,2007-01-01 12:08:37+00:00,2007-01-01 12:08:37+00:00,23768af19dc69992,PRESS DIGEST - New York Times - Jan 1,3,1,RTRS,"{'PUB', 'BUS', 'INS', 'CA', 'ENT', 'US', 'FIN'...","{'M', 'PMF', 'DNP', 'PTD', 'T', 'E', 'D', 'PSC...",...,0,0,0,0,0,0,0,5,13,15
4,2007-01-01 12:08:37+00:00,2007-01-01 12:08:37+00:00,2007-01-01 12:08:37+00:00,23768af19dc69992,PRESS DIGEST - New York Times - Jan 1,3,1,RTRS,"{'PUB', 'BUS', 'INS', 'CA', 'ENT', 'US', 'FIN'...","{'M', 'PMF', 'DNP', 'PTD', 'T', 'E', 'D', 'PSC...",...,0,0,0,0,0,0,0,0,0,0

In [6]:
mktdata_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 16 columns):
time                        100 non-null object
assetCode                   100 non-null object
assetName                   100 non-null object
universe                    100 non-null float64
volume                      100 non-null float64
close                       100 non-null float64
open                        100 non-null float64
returnsClosePrevRaw1        100 non-null float64
returnsOpenPrevRaw1         100 non-null float64
returnsClosePrevMktres1     0 non-null float64
returnsOpenPrevMktres1      0 non-null float64
returnsClosePrevRaw10       100 non-null float64
returnsOpenPrevRaw10        100 non-null float64
returnsClosePrevMktres10    0 non-null float64
returnsOpenPrevMktres10     0 non-null float64
returnsOpenNextMktres10     100 non-null float64
dtypes: float64(13), object(3)
memory usage: 12.6+ KB

In [7]:
news_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 35 columns):
time                    100 non-null object
sourceTimestamp         100 non-null object
firstCreated            100 non-null object
sourceId                100 non-null object
headline                100 non-null object
urgency                 100 non-null int64
takeSequence            100 non-null int64
provider                100 non-null object
subjects                100 non-null object
audiences               100 non-null object
bodySize                100 non-null int64
companyCount            100 non-null int64
headlineTag             36 non-null object
marketCommentary        100 non-null bool
sentenceCount           100 non-null int64
wordCount               100 non-null int64
assetCodes              100 non-null object
assetName               100 non-null object
firstMentionSentence    100 non-null int64
relevance               100 non-null float64
sentimentClass          100 non-null int64
sentimentNegative       100 non-null float64
sentimentNeutral        100 non-null float64
sentimentPositive       100 non-null float64
sentimentWordCount      100 non-null int64
noveltyCount12H         100 non-null int64
noveltyCount24H         100 non-null int64
noveltyCount3D          100 non-null int64
noveltyCount5D          100 non-null int64
noveltyCount7D          100 non-null int64
volumeCounts12H         100 non-null int64
volumeCounts24H         100 non-null int64
volumeCounts3D          100 non-null int64
volumeCounts5D          100 non-null int64
volumeCounts7D          100 non-null int64
dtypes: bool(1), float64(4), int64(19), object(11)
memory usage: 26.7+ KB

In [8]:
mktdata_df.assetCode.value_counts()

AJG.N     1
ADM.N     1
AMAT.O    1
APA.N     1
AEP.N     1
AH.N      1
AMTD.O    1
AGE.N     1
AKR.N     1
ANDE.O    1
AEA.N     1
ABT.N     1
AD.N      1
APH.N     1
AMP.N     1
APPB.O    1
ADCT.O    1
APKT.O    1
AMKR.O    1
ABM.N     1
ACS.N     1
ALU.N     1
AINV.O    1
ABY.N     1
AEL.N     1
AIN.N     1
APOL.O    1
AHL.N     1
AOS.N     1
AMX.N     1
         ..
ACXM.O    1
ABD.N     1
APC.N     1
A.N       1
AIT.N     1
AHG.N     1
AMLN.O    1
ADI.N     1
AMD.N     1
ALB.N     1
AG.N      1
ADTN.O    1
ALD.N     1
ACH.N     1
AFFX.O    1
ACL.N     1
AMZN.O    1
AEE.N     1
AKS.N     1
AEIS.O    1
AIZ.N     1
AFG.N     1
ALV.N     1
AER.N     1
AAI.N     1
AET.N     1
AGN.N     1
AFL.N     1
AES.N     1
AOC.N     1
Name: assetCode, Length: 100, dtype: int64

In [9]:
from kaggle.competitions import twosigmanews
env = twosigmanews.make_env()

Warning: Your Kaggle API key is readable by other users on this system! To fix this, you can run 'chmod 600 /Users/hao.yan/.kaggle/kaggle.json'

ModuleNotFoundError: No module named 'kaggle.competitions'